version: '3.9'

services:
  products-db:
    container_name: products_database
    image: postgres:16.3
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=E_COMMERCE_PRODUCTS